#!/usr/bin/env zsh

nodes=( .zsh .zshrc .vim .vimrc )

for node in $nodes; do
    if [[ -a $HOME/$node ]]; then
        echo "$node already exist in your home dir. Do you want to override it? (y/n)"
        read -q res
        echo $'\n'
        if [ $res = 'y' ]; then
            if [[ -L $HOME/$node ]]; then
                unlink $HOME/$node
            else
                rm -rf $HOME/$node
            fi

            ln -s $HOME/.dotfiles/$node $HOME/$node
        fi
    else
        ln -s $HOME/.dotfiles/$node $HOME/$node
    fi
done
