PS1='%{%F{magenta}%}[%{%f%}'
PS1="$PS1%{%F{green}%}%!%{%f%}"
PS1="$PS1%{%F{magenta}%}]%{%f%}"
#PS1="$PS1%{%F{red}%}@%{%f%}"
PS1="$PS1%{%F{blue}%}[%{%f%}"
PS1="$PS1%{%F{yellow}%}%~%{%f%}"
PS1="$PS1%{%F{blue}%}]%{%f%} "
PS1="$PS1%{%F{cyan}%}%#%{%f%} "
#PS1="$PS1%{%F{white}%}"
