#! /bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

bspc wm -a eDP1

if [[ $(xrandr -q | grep 'HDMI-1-0 connected') ]];
then
  bspc wm -a HDMI-1-0 
  bspc monitor eDP1 	    -d 1 2 3 4 5
  bspc monitor 'HDMI-1-0' -d 6 7 8 9 0
else
  bspc monitor eDP1 	-d 1 2 3 4 5 6 7 8 9 0
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
