#! /bin/bash

if (cat /etc/os-release | grep 'Void Linux')
then
  firstmon='eDP1'
  pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/sxhkd/sxhkdrc_void &
else
  firstmon='eDP-1'
  pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/sxhkd/sxhkdrc_debian &
fi

picom &

secondmon='HDMI-1-0'

if (xrandr -q | grep "$secondmon connected")
then
  xrandr --output $firstmon --primary --output $secondmon --auto --right-of $firstmon
  bspc monitor $firstmon -d 1 2 3 4 5
  bspc monitor $secondmon -d 6 7 8 9 0
else
  bspc monitor -d 1 2 3 4 5 6 7 8 9 0
fi

nitrogen --restore

if (cat /etc/os-release | grep 'Void Linux')
then
  pipewire &
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a 'Virt-manager':'virt-manager':* state=floating follow=on
